/*
 * Copyright (c) 2025 James S. Clark
 *
 * This is private source code.  You may not use, copy, or distribute this file under any circumstances without written
 * permission from the copyright holder, depicted above. All rights reserved.
 */

/*
 * This source file was generated by the Gradle 'init' task
 */
package com.planetscale.debezium

public object PlanetscaleDebezium {
    public fun setup(): Boolean {
        return true
    }
}
