#
# Copyright (c) 2025 James S. Clark
#
# This is private source code.  You may not use, copy, or distribute this file under any circumstances without written
# permission from the copyright holder, depicted above. All rights reserved.
#

version=3.1.2.Final
debeziumVersion=3.1.2.Final

elidePluginVersion=latest
kotlin.jvm.target.validation.mode=ignore

org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configureondemand = true
org.gradle.jvmargs = -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -Xmx24g --add-opens=java.base/java.util.function=ALL-UNNAMED \
  --add-opens=java.base/java.util.stream=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.\
  base/java.nio.channels=ALL-UNNAMED --add-opens=java.base/java.nio.channels.spi=ALL-UNNAMED --add-opens=java.base/java.\
  util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/java.\
  lang.ref=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED \
  --enable-native-access=ALL-UNNAMED
org.gradle.unsafe.isolated-projects = false
org.gradle.configuration-cache = true
org.gradle.configuration-cache.parallel = false
org.gradle.configuration-cache.problems = warn
org.gradle.configuration-cache.stable = true
org.gradle.configuration-cache.max-problems = 1000
org.gradle.dependency.verification = off
org.gradle.workers.max = 8
org.gradle.warning.mode = none
