#
# Copyright (c) 2025 James S. Clark
#
# This is private source code.  You may not use, copy, or distribute this file under any circumstances without written
# permission from the copyright holder, depicted above. All rights reserved.
#

[versions]
bytebuddy = "1.18.3"
commons-math3 = "3.6.1"
googleJavaFormat = "1.28.0"
mysql-connector-j = "9.2.0"
grpc = "1.56.1"
guava = "33.4.8-jre"
junit-jupiter-engine = "6.0.1"
kafka-connect-api = "3.9.0"
kotlin = "2.2.21"
kotlinx-abicheck = "0.18.1"
kotlinx-atomicfu = "0.29.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-io = "0.8.0"
kotlinx-kover = "0.9.4"
ktfmt = "0.56"
ktlint = "1.0.0"
netty = "4.1.87.Final"
tcnative = "2.0.61.Final"
shadow = "8.3.8"
sigstore = "1.3.0"
spdx = "0.9.0"
spotless = "7.2.1"
testcontainers = "1.21.4"
testlogger = "4.0.0"
vitess-client = "22.0.1"

[libraries]
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
vitess-grpc-client = { module = "io.vitess:vitess-grpc-client", version.ref = "vitess-client" }
grpc-core = { module = "io.grpc:grpc-core", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-auth = { module = "io.grpc:grpc-auth", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
kafka-connect-api = { module = "org.apache.kafka:connect-api", version.ref = "kafka-connect-api" }
mysql-connector-j = { module = "com.mysql:mysql-connector-j", version.ref = "mysql-connector-j" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
kotlinx-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-atomicfu-jvm = { group = "org.jetbrains.kotlinx", name = "atomicfu-jvm", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinx-io" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
netty-transport-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }

# Plugins.
plugin-bytebuddy = { module = "net.bytebuddy:byte-buddy-gradle-plugin", version.ref = "bytebuddy" }
plugin-kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-atomicfu = { module = "org.jetbrains.kotlin.plugin.atomicfu:org.jetbrains.kotlin.plugin.atomicfu.gradle.plugin", version.ref = "kotlin" }
plugin-kotlin-powerAssert = { module = "org.jetbrains.kotlin.plugin.power-assert:org.jetbrains.kotlin.plugin.power-assert.gradle.plugin", version.ref = "kotlin" }
plugin-kotlinx-atomicfu = { module = "org.jetbrains.kotlinx.atomicfu:org.jetbrains.kotlinx.atomicfu.gradle.plugin", version.ref = "kotlinx-atomicfu" }
plugin-kotlinx-kover = { module = "org.jetbrains.kotlinx.kover:org.jetbrains.kotlinx.kover.gradle.plugin", version.ref = "kotlinx-kover" }
plugin-spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
plugin-testlogger = { module = "com.adarshr.test-logger:com.adarshr.test-logger.gradle.plugin", version.ref = "testlogger" }

# Internal library references.
planetscale-debezium = { module = "com.planetscale.labs:debezium-planetscale" }
planetscale-debezium-facade = { module = "com.planetscale.labs:facade" }
planetscale-debezium-transformer = { module = "com.planetscale.labs:transformer" }
planetscale-debezium-transforms = { module = "com.planetscale.labs:transforms" }

[plugins]
bytebuddy = { id = "net.bytebuddy.byte-buddy-gradle-plugin", version.ref = "bytebuddy" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-powerAssert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
kotlinx-abicheck = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-abicheck" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
planetscale-debezium = { id = "com.planetscale.debezium" }
planetscale-debezium-build = { id = "com.planetscale.debezium.conventions" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sigstore = { id = "dev.sigstore.sign", version.ref = "sigstore" }
spdx = { id = "org.spdx.sbom", version.ref = "spdx" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
testlogger = { id = "com.adarshr.test-logger", version.ref = "testlogger" }

[bundles]
bytebuddy = [
  "bytebuddy"
]

kotlinx = [
  "kotlinx-atomicfu-jvm",
  "kotlinx-coroutines-core",
  "kotlinx-coroutines-jdk8",
  "kotlinx-datetime",
  "kotlinx-io",
  "kotlinx-io-bytestring",
]

vitess-client = [
  "vitess-grpc-client",
  "grpc-core",
  "grpc-stub",
  "grpc-auth"
]
