debezium.format.value=json

debezium.sink.type=http
debezium.sink.http.url=http://127.0.0.1:8888/post

debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=data/schema_history.dat

debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=0

debezium.source.database.hostname=aws.connect.psdb.cloud
debezium.source.database.port=443
debezium.source.database.user=(planetscale user)
debezium.source.database.password=(planetscale password)

debezium.source.vitess.keyspace=(database name)

debezium.source.connector.class=com.planetscale.debezium.PlanetscaleConnector
debezium.source.topic.prefix=(topic name)

debezium.tasks.max=1
