/*
 * This source file was generated by the Gradle 'init' task
 */
package com.planetscale.debezium

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
  @Test fun someLibraryMethodReturnsTrue() {
    assertTrue(PlanetscaleDebezium.setup(), "someLibraryMethod should return 'true'")
  }
}
