name: "Build"

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        default: "ubuntu-latest"
      release:
        description: "Release"
        default: false
        type: boolean
      provenance:
        description: "SLSA Provenance"
        required: false
        default: false
        type: boolean
      graph:
        description: "Dependency Graph"
        required: false
        default: "generate-submit-and-upload"
        type: string
      build:
        description: "Build"
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: "ubuntu-latest"
      release:
        required: false
        default: false
        type: boolean
      provenance:
        required: false
        default: false
        type: boolean
      graph:
        description: "Dependency Graph"
        required: false
        default: "disabled"
        type: string
      cache_read_only:
        description: "Cache: Read Only"
        required: false
        type: string
        default: "false"
      build:
        description: "Build"
        required: false
        default: true
        type: boolean

    outputs:
      checksums:
        description: "Checksums"
        value: ${{ jobs.build-and-test.outputs.hashes }}
    secrets:
      GRADLE_ENCRYPTION_KEY:
        description: "Gradle Encryption Key"
        required: false
      CODECOV_TOKEN:
        description: "Codecov Token"
        required: true

permissions:
  contents: read

concurrency:
  group: build-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: "Build and Test"
    if: inputs.build
    runs-on: ${{ inputs.runner || vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
    permissions:
      contents: read
      checks: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.azul.com:443
            api.github.com:443
            cdn.azul.com:443
            dl.google.com:443
            gha.elide.zip:443
            github.com:443
            gradle.elide.dev:443
            maven.elide.dev:443
            objects.githubusercontent.com:443
            plugins-artifacts.gradle.org:443
            plugins.gradle.org:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
            scans-in.gradle.com:443
            services.gradle.org:443
            spdx.org:443
            telemetry.elide.dev:443
      - name: "Setup: Checkout"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup: JVM"
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ vars.JAVA_TOOLCHAIN_VERSION || '24' }}
          distribution: ${{ vars.JAVA_TOOLCHAIN_VENDOR || 'graalvm' }}
      - name: "Setup: Elide"
        uses: elide-dev/setup-elide@a62ce5ca052e16ecd1c6eb3f2efde2e0228d5e80 # main
      - name: "Setup: Gradle"
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
        with:
          dependency-graph: ${{ inputs.graph || 'disabled' }}
          dependency-graph-continue-on-failure: 'true'
          cache-overwrite-existing: true
          cache-read-only: ${{ inputs.cache_read_only || 'true' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: "Check: Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      - name: "Outputs: Short SHA"
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: "Build: Gradle"
        run: ./gradlew --scan build test check
      - name: "Report: Tests (GHA)"
        uses: elide-tools/action-junit-report@d8d34855fefcfd2a15b5005b4cca125da5b41c8c
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: "Report: Tests (Codecov)"
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Report: Coverage (Codecov)"
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          files: ./*/build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: "Artifact: Maven Repository"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: maven-repository-${{ steps.vars.outputs.sha_short || 'latest' }}
          path: ./debezium-planetscale/build/m2
          retention-days: 1
          compression-level: 2
      - name: "Artifact: Shadow JAR"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: connector-${{ steps.vars.outputs.sha_short || 'latest' }}.jar
          path: ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar
          compression-level: 0
      - name: "Artifact: SBOM"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sbom-${{ steps.vars.outputs.sha_short || 'latest' }}.spdx.json
          path: ./debezium-planetscale/build/spdx/release.spdx.json
          compression-level: 6
      - name: "Artifact: Checksums"
        shell: bash
        id: hash
        run: |
          echo "hashes=$(sha256sum ./debezium-planetscale/build/spdx/release.spdx.json ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    name: "SLSA"
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    needs: [build-and-test]
    if: inputs.build && inputs.provenance
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    with:
      base64-subjects: "${{ needs.build-and-test.outputs.hashes }}"
      upload-assets: ${{ inputs.release }}
      private-repository: true
