name: "Build"

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        default: "ubuntu-latest"
      release:
        description: "Release"
        default: false
        type: boolean
      provenance:
        description: "Build Provenance"
        required: false
        default: false
        type: boolean
      graph:
        description: "Dependency Graph"
        required: false
        default: "generate-submit-and-upload"
        type: string
      build:
        description: "Build"
        required: false
        default: true
        type: boolean

  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: "ubuntu-latest"
      release:
        required: false
        default: false
        type: boolean
      provenance:
        required: false
        default: false
        type: boolean
      graph:
        description: "Dependency Graph"
        required: false
        default: "disabled"
        type: string
      cache_read_only:
        description: "Cache: Read Only"
        required: false
        type: string
        default: "false"
      build:
        description: "Build"
        required: false
        default: true
        type: boolean

    outputs:
      checksums:
        description: "Checksums"
        value: ${{ jobs.build-and-test.outputs.hashes }}
    secrets:
      GRADLE_ENCRYPTION_KEY:
        description: "Gradle Encryption Key"
        required: false
      CODECOV_TOKEN:
        description: "Codecov Token"
        required: true
      CONFLUENT_CLOUD_API_KEY:
        description: "Confluent Cloud API Key"
        required: false
      CONFLUENT_CLOUD_API_SECRET:
        description: "Confluent Cloud API Secret"
        required: false
      CONFLUENT_ENV:
        description: "Confluent Environment ID"
        required: false
      CONFLUENT_CLUSTER:
        description: "Confluent Cluster ID"
        required: false

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: "Build and Test"
    if: inputs.build
    runs-on: ${{ inputs.runner || vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
    permissions:
      contents: read
      checks: write
      id-token: write
      attestations: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.azul.com:443
            api.github.com:443
            auth.docker.io:443
            cdn.azul.com:443
            dl.google.com:443
            gha.elide.zip:443
            ghcr.io:443
            github.com:443
            gradle.elide.dev:443
            maven.elide.dev:443
            production.cloudflare.docker.com:443
            quay.io:443
            registry-1.docker.io:443
            objects.githubusercontent.com:443
            plugins-artifacts.gradle.org:443
            plugins.gradle.org:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            repo.maven.apache.org:443
            scans-in.gradle.com:443
            services.gradle.org:443
            spdx.org:443
            telemetry.elide.dev:443
      - name: "Setup: Checkout"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup: JVM"
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: ${{ vars.JAVA_TOOLCHAIN_VERSION || '25' }}
          distribution: ${{ vars.JAVA_TOOLCHAIN_VENDOR || 'graalvm' }}
      - name: "Setup: Elide"
        uses: elide-dev/setup-elide@d2f742321bf672300c0935839b6f5c6e562a965b # v4.1.0
      - name: "Setup: Gradle"
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v4
        with:
          dependency-graph: ${{ inputs.graph || 'disabled' }}
          dependency-graph-continue-on-failure: 'true'
          cache-overwrite-existing: true
          cache-read-only: ${{ inputs.cache_read_only || 'true' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: "Check: Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v4
      - name: "Outputs: Short SHA"
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: "Build: Gradle"
        run: ./gradlew --scan build test check connectDist
      - name: "Report: Tests (GHA)"
        uses: elide-tools/action-junit-report@d8d34855fefcfd2a15b5005b4cca125da5b41c8c
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: "Report: Tests (Codecov)"
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: "Report: Coverage (Codecov)"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: ./*/build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: "Artifact: Maven Repository"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
        with:
          name: maven-repository-${{ steps.vars.outputs.sha_short || 'latest' }}
          path: ./debezium-planetscale/build/m2
          retention-days: 1
          compression-level: 2
      - name: "Artifact: Shadow JAR"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
        with:
          name: connector-${{ steps.vars.outputs.sha_short || 'latest' }}.jar
          path: ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar
          compression-level: 0
      - name: "Artifact: Connect ZIP"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
        with:
          name: connect-zip-${{ steps.vars.outputs.sha_short || 'latest' }}
          path: ./debezium-planetscale/build/connect/dist/*.zip
          compression-level: 0
      - name: "Artifact: SBOM"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
        with:
          name: sbom-${{ steps.vars.outputs.sha_short || 'latest' }}.spdx.json
          path: ./debezium-planetscale/build/spdx/release.spdx.json
          compression-level: 6
      - name: "Artifact: Checksums"
        shell: bash
        id: hash
        run: |
          echo "hashes=$(sha256sum ./debezium-planetscale/build/spdx/release.spdx.json ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar | base64 -w0)" >> "$GITHUB_OUTPUT"
      - name: "Attest: JAR Provenance"
        if: inputs.provenance
        continue-on-error: true # requires public repo
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v2
        with:
          subject-path: ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar
      - name: "Attest: Connect ZIP Provenance"
        if: inputs.provenance
        continue-on-error: true # requires public repo
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v2
        with:
          subject-path: ./debezium-planetscale/build/connect/dist/*.zip
      - name: "Attest: SBOM"
        if: inputs.provenance
        continue-on-error: true # requires public repo
        uses: actions/attest-sbom@bd218ad0dbcb3e146bd073d1d9c6d78e08aa8a0b # v2
        with:
          subject-path: ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar
          sbom-path: ./debezium-planetscale/build/spdx/release.spdx.json
