name: "Deploy - Maven"

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: "ubuntu-latest"
      artifact:
        required: true
        type: string
      bucket:
        required: true
        type: string
        default: "planetscale-maven-dev"
      run_id:
        required: false
        type: string
    secrets:
      S3_ACCESS_KEY_ID:
        required: true
        description: "S3 Access Key ID"
      S3_SECRET_ACCESS_KEY:
        required: true
        description: "S3 Secret Access Key"

  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        required: false
        type: string
        default: "ubuntu-latest"
      artifact:
        description: "Artifact"
        required: true
        type: string
      bucket:
        description: "Bucket"
        required: true
        type: string
        default: "planetscale-maven-dev"
      run_id:
        required: false
        type: string
        description: "Run ID"
      environment:
        description: "Environment"
        required: true
        default: sandbox

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.sha }}
  cancel-in-progress: true

jobs:
  deploy-to-r2:
    name: "Maven"
    runs-on: ${{ inputs.runner }}
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      actions: read
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          disable-sudo: true
          egress-policy: audit
      - name: "Setup: Artifacts"
        id: download
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ inputs.artifact }}
          merge-multiple: 'true'
          run-id: ${{ inputs.run_id || github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup: Authorization"
        run: |
          echo "[r2]" >> /tmp/rclone.conf
          echo "type = s3" >> /tmp/rclone.conf
          echo "provider = Cloudflare" >> /tmp/rclone.conf
          echo "access_key_id = ${{ secrets.S3_ACCESS_KEY_ID }}" >> /tmp/rclone.conf
          echo "secret_access_key = ${{ secrets.S3_SECRET_ACCESS_KEY }}" >> /tmp/rclone.conf
          echo "region = auto" >> /tmp/rclone.conf
          echo "endpoint = ${{ vars.S3_ENDPOINT }}" >> /tmp/rclone.conf
      - name: "Deploy: Maven"
        run: |
          wget https://github.com/rclone/rclone/releases/download/v1.69.3/rclone-v1.69.3-linux-amd64.zip
          mkdir /tmp/rclone
          unzip rclone-v1.69.3-linux-amd64.zip -d /tmp/rclone
          cd "${{ steps.download.outputs.download-path }}"
          /tmp/rclone/rclone --config $GITHUB_WORKSPACE/rclone.conf copy --progress . r2:${{ inputs.bucket }}
