name: "Build"

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        default: "ubuntu-latest"
      release:
        description: "Release"
        default: false
        type: boolean
      provenance:
        description: "SLSA Provenance"
        required: false
        default: false
        type: boolean

  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: "ubuntu-latest"
      release:
        required: false
        default: false
        type: boolean
      provenance:
        required: false
        default: false
        type: boolean
    outputs:
      checksums:
        description: "Checksums"
        value: ${{ jobs.build-and-test.outputs.hashes }}

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    permissions:
      contents: read
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.azul.com:443
            api.github.com:443
            cdn.azul.com:443
            dl.google.com:443
            gha.elide.zip:443
            github.com:443
            gradle.elide.dev:443
            maven.elide.dev:443
            objects.githubusercontent.com:443
            plugins-artifacts.gradle.org:443
            plugins.gradle.org:443
            raw.githubusercontent.com:443
            repo.maven.apache.org:443
            scans-in.gradle.com:443
            services.gradle.org:443
            spdx.org:443
            telemetry.elide.dev:443
      - name: "Setup: Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: "Setup: JVM"
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: "Setup: Elide"
        uses: elide-dev/setup-elide@a62ce5ca052e16ecd1c6eb3f2efde2e0228d5e80 # main
      - name: "Setup: Gradle"
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4
        with:
          dependency-graph: 'generate-submit-and-upload'
          dependency-graph-continue-on-failure: 'true'
          cache-disabled: 'true'
      - name: "Check: Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4
      - name: "Outputs: Short SHA"
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: "Build: Gradle"
        run: ./gradlew --no-daemon --scan build test check
      - name: "Artifact: Maven Repository"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: maven-repository-${{ steps.vars.outputs.sha_short || 'latest' }}
          path: ./debezium-planetscale/build/m2
          retention-days: 1
          compression-level: 2
      - name: "Artifact: Shadow JAR"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: connector-${{ steps.vars.outputs.sha_short || 'latest' }}.jar
          path: ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar
          compression-level: 0
      - name: "Artifact: SBOM"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sbom-${{ steps.vars.outputs.sha_short || 'latest' }}.spdx.json
          path: ./debezium-planetscale/build/spdx/release.spdx.json
          compression-level: 6
      - name: "Artifact: Checksums"
        shell: bash
        id: hash
        run: |
          echo "hashes=$(sha256sum ./debezium-planetscale/build/spdx/release.spdx.json ./debezium-planetscale/build/libs/planetscale-debezium-adapter-*.jar | base64 -w0)" >> "$GITHUB_OUTPUT"

  provenance:
    name: "SLSA"
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    needs: [build-and-test]
    if: inputs.provenance
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    with:
      base64-subjects: "${{ needs.build-and-test.outputs.hashes }}"
      upload-assets: ${{ inputs.release }}
      private-repository: true
