name: "CI"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '*.md'
      - '**/*.md'
      - 'docs/**/*.*'
      - '.github/*.md'
      - '.github/workflows/claude.yml'
      - '.github/workflows/job.review.yml'
      - '.github/workflows/job.deploy-repo.yml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/job.build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    permissions:
      actions: read # Needed for detection of GitHub Actions environment (SLSA).
      contents: write # Needed for provenance signing and ID (SLSA).
      id-token: write # Needed for release uploads (SLSA).
      checks: write # Needed for test result publishing.
    with:
      provenance: true
